Evan Haryowidyatna / 2006485011

## TUGAS 5 Praktikum MetNum
Tugas anda adalah membuat program yang dapat menyelesaikan SPL, dengan input berupa
matrix 4 x 5 dengan ketentuan sebagai berikut:
- Elemen elemen baris pertama hingga ketiga adalah hasil random, dengan

aij ∈ Z, |aij| < 100
- Baris terakhir berisi 5 digit terakhir NPM anda

### Penjelasan Program
Program ini digunakan untuk menyelesaikan spl yang salah satu inputnya merupakan 5 nomor terakhir di npm kita

1. Mengimpor modul yang akan digunakan di program
2. Membuat matriks di augmatrix sesuai yang diminta di soal yaitu berukuran 4x5 dimana 3 baris pertama random dan baris terakhir inputnya adalah 5 nomor terakhir NPM kita
3. Mendefinisikan fungsi Partial untuk melakukan partial pivoting sesuai dengan yang sudah di pelajari
4. Mengecek apakah dalam matriks ada yang elemennya 0 jika iya maka SPL tidak memiliki solusi karena ada yang barisnya inputnya 0 dan bila tidak ada 0  maka akan dijalankan dengan cara partial pivoting seperti yang sudah di jelaskan sebelumnya
5. Melakukan eliminasi gauss dengan program yang sudah dibuat untuk menemukan hasil SPL nya 
6.  Mendefinisikan variabel triangular_form yaitu matriks diperbesar yang sudah dieliminasi, maka program akan mencari seluruh solusi dengan BackSubs dan mengeluarkan hasilnya.



In [17]:
import numpy as np #mengimpor modul agar program bisa dijalankan

NPM = eval(input('masukkan 5 nomor terakhir di npm mu dalam bentuk list contohnya [1,2,3,4]: '))

augmatrix = [] #membuat matriks
for i in range (3): #membuat banyak baris
  entry = []
  for j in range(5): #membuat banyak kolom
    entry.append(np.random.randint(-99,100)) #membuat batas input
  augmatrix.append(entry)
augmatrix.append(NPM) #memasukkan 5 nomor terakhir di npm
augmatrix = np.array(aug_matrix)
print(augmatrix) #mengeluarkan matriks
print('')

def Partial(matrix):
    n = np.shape(matrix)[0] #banyak baris/persamaan pada matrix
    for i in range(n-1):
        below_pivot = abs(matrix[i:,i])  # Mencari lokasi dari kolom yg membuat absolutnya nilai maksimum
        
        pivot_row = np.argmax(below_pivot)
        
        if matrix[i,pivot_row+i] == 0:    #jika nilainya = 0, satu kolom bernilai 0
            return "Tidak ada solusi unik"
        else:
            matrix[[pivot_row+i,i]]= matrix[[i,pivot_row+i]]
            
        for j in range(i+1,n):       #melakukan eliminasi gauss
            m = matrix[j,i]/matrix[i,i]
            matrix[j] = matrix[j]-m*matrix[i]
        print(matrix)
        print('')
    return matrix

def BackSubs(matrix):
    n = np.shape(matrix)[0]  #menentukan banyak baris pada matrix
    sol = np.zeros(n)  #membentuk array [0] sepanjang n, untuk menyimpan solusi
    sol[n-1]= matrix[n-1,n]/matrix[n-1,n-1]
    for i in range(n-2,-1,-1):
        for j in range(i+1,n):
            matrix[i,n]-=matrix[i,j]*sol[j]
        sol[i] = matrix[i,n]/matrix[i,i]
    return sol

triangular_form_pp = Partial(aug_matrix)
print("Solusi SPL : \n {0}".format(BackSubs(triangular_form_pp))) #mengeluarkan hasil

masukkan 5 nomor terakhir di npm mu dalam bentuk list contohnya [1,2,3,4]: [8,5,0,1,1]
[[    95     25     83     80 -12220]
 [     0    -47     62    101  -3598]
 [     0      0    -45    -44   -664]
 [     0      0      0      2     -3]]

[[    95     25     83     80 -12220]
 [     0    -47     62    101  -3598]
 [     0      0    -45    -44   -664]
 [     0      0      0      2     -3]]

[[    95     25     83     80 -12220]
 [     0    -47     62    101  -3598]
 [     0      0    -45    -44   -664]
 [     0      0      0      2     -3]]

[[    95     25     83     80 -12220]
 [     0    -47     62    101  -3598]
 [     0      0    -45    -44   -664]
 [     0      0      0      2     -3]]

Solusi SPL : 
 [-166.45263158   94.70212766   16.22222222   -1.5       ]
